### ISSUE TITLE
White screen on Android

### ISSUE THREAD

**Issue by angel1st** [mauron85/cordova-plugin-background-geolocation-example#17]
Hi there,
I just checked out the code, followed the instructions and compiled an Android debug apk. When it was installed on the device (Android 8.0.0), I ended up with white screen.
Console log says:

`TypeError: (0 , o.default)(...).darken(...).hex is not a function
app.js:1
    at Object.get statusBarColor [as statusBarColor] (file:///android_asset/www/app.js:1:4701)
    at file:///android_asset/www/app.js:1:36865
    at fr (file:///android_asset/www/app.js:1:27433)
    at file:///android_asset/www/app.js:1:36667
    at Function.ll (file:///android_asset/www/app.js:1:52475)
    at e (file:///android_asset/www/app.js:11:234047)
    at file:///android_asset/www/app.js:11:234184
    at file:///android_asset/www/app.js:1:36862
    at fr (file:///android_asset/www/app.js:1:27433)
    at file:///android_asset/www/app.js:1:36667`

Any help would be appreciated.

**Comment by mauron85** [comment]
Delete node modules folder and do fresh modules install

**Comment by angel1st** [comment]
Nope, it didn't work.
What I did:
1. Deleted `node_modules` folder
1. Executed `npm install`
1. Started app in debug mode --> received the exact same error as above.

**Comment by mauron85** [comment]
you need to rebuild app too:

npm run build

**Comment by angel1st** [comment]
@mauron85  - no luck again. 
BTW - sorry if I am asking for the obvious, but how repeating the steps which failed to deliver exception free app once will fix it on the next iteration?

**Comment by mauron85** [comment]
There is another suggestion in https://github.com/mauron85/cordova-plugin-background-geolocation-example/issues/16. I believe this is some kind of dependency issues, where two packages are using conflicting dependency. Don't think I can do much here.

**Comment by mauron85** [comment]
Basically guy used yarn instead of npm.

**Comment by angel1st** [comment]
Thanks,
So basically, as mentioned in #16, the actual reason is having `package-lock.json` which in fact caused this dependencies mismatch.
The workaround on this issue is:
1. Delete `node_modules` folder
1. Install packages using `yarn`
1. Build the app using `npm run build`

@mauron85 - I do agree with @pmatheush the best would be to update the readme file, this will save you from further identical inquiries.

**Comment by mauron85** [comment]
You probably ment there is no package-lock.json but yarn.lock. Anyway, there should be no need to have any of those lock files.. Apparently there is some dependency issue problem as reported in https://github.com/GeekyAnts/NativeBase/issues/1354

**Comment by angel1st** [comment]
Actually, `package-lock.json` is generated automatically, whenever npm 5.x.x+ command is used e.g. `npm install`. This is according to [npm documentation](https://docs.npmjs.com/files/package-lock.json).
When `yarn` is used instead of `npm install`, `package-lock.json` creation is skipped, hence subsequent `npm run build` produces a runnable app.
