### ISSUE TITLE
Crahs on Android 8.1.0

### ISSUE THREAD

**Issue by jondediego** [mauron85/cordova-plugin-background-geolocation-example#22]
Hi,
Should this plugin work on Andoid 8.1.0?. For 7.x version it is working for me, but for 8.1.0, the app crashes for me whenever I call to start method of this plugin.
This is the error I get on Android Studio logcat:
```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.suez.galiaMovile, PID: 31963
                                                                      android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 number=0 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1893)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                          at android.os.Looper.loop(Looper.java:164)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6960)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

**Comment by ThibertT** [comment]
Same Here, not on a particular Android Version but for some devices running Android. 
App crashes when calling start method.

**Comment by tavor8** [comment]
+1

**Comment by jondediego** [comment]
It works for me using the new alpha version of this plugin

**Comment by tavor8** [comment]
thanks a lot, I was using v2.3.6, now issue is gone after using the alpha version. thx for letting me know that.

**Comment by marcosvcr84** [comment]
@tavor8  how did you install alpha version that worked for you?
