### ISSUE TITLE
 Could not install from "@mauron85/cordova-plugin-background-geolocation@~3.1.0" as it does not contain a package.json file.

### ISSUE THREAD

**Issue by mitLinkwok** [mauron85/cordova-plugin-background-geolocation-example#32]
{ Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@mauron85/cordova-plugin-background-geolocation@~3.1.0" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mit/.npm/_logs/2020-01-30T09_33_11_614Z-debug.log
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  stderr:
   'npm ERR! code ENOLOCAL\nnpm ERR! Could not install from "@mauron85/cordova-plugin-background-geolocation@~3.1.0" as it does not contain a package.json file.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!

**Comment by giuliastully** [comment]
I have same problem. How can you solve it?

**Comment by hatimox** [comment]
hello @giuliastully @mitLinkwok i just found the solution [here](https://github.com/mauron85/cordova-plugin-background-geolocation/issues/663#issuecomment-621601544)
